name: Docker CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t test-automation .

      - name: Run Docker container
        run: |
          docker run --rm test-automation
        
      - name: Push Docker image to Docker Hub
        run: |
          docker tag test-automation ${{ secrets.DOCKER_USERNAME }}/test-automation:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/test-automation:latest
        if: github.ref == 'refs/heads/main'
